name: Terraform Setup
description: Install Terraform, AWS CLI, TFLint and Checkov

inputs:
  terraform-version:
  required: false
  default: "1.12.2"

runs:
  using: composite

  steps:    
    - name: Install Checkov Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        python3 \
        python3-pip \
        python3-venv \
        python3-full
        python3 -m venv .checkov-env
        .checkov-env/bin/python -m pip install --upgrade pip
        .checkov-env/bin/pip install checkov
        .checkov-env/bin/checkov --version