name: Test Pipeline
run-name: Testing github actions

on:
  workflow_dispatch:

jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage One Completed"

  approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: stage-one
    environment: prod-approval
    steps:
      - run: echo "Waiting for approval"

  stage-two:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - run: echo "Approved - Moving to next stage"