name: Test Pipeline
run-name: Testing github actions

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-prod
  cancel-in-progress: false

pre-requisites:
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::277802554635:role/GITHUB_ODIC_AUTH
    aws-region: us-east-1

on:
  workflow_dispatch:

jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage One Completed"
  
      
    
