name: Test Pipeline
run-name: Testing github actions

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the action to perform"
        required: true
        type: choice
        options:
          - apply
          - remove
      confirmation:
        description: "Type APPROVED to confirm the action"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "APPROVED" ]; then
            echo "Approval failed"
            exit 1
          fi

          terraform apply \
            --var-file=variables/prod.tfvars \
            -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "APPROVED" ]; then
            echo "Approval failed"
            exit 1
          fi

          if [ "${{ github.event.inputs.destroy_type }}" = "all" ]; then

            terraform destroy \
              --var-file=variables/prod.tfvars \
              -auto-approve

          elif [ "${{ github.event.inputs.destroy_type }}" = "target" ]; then

            terraform destroy \
              --var-file=variables/prod.tfvars \
              -target="${{ github.event.inputs.target_resource }}" \
              -auto-approve

          fi